### ISSUE TITLE
factotum-job_worker-apihub_scraper_throttled queue is not operating nominally

### ISSUE THREAD

**Issue by jjmcnelis** [aria-jpl/scihub_acquisition_scraper#13]
# *scihub_acquisition_scraper* jobs are not processing on factotum queues

## description

* the *apihub_scraper_throttled* worker queue on factotum appears to be "stuck" -- i.e. not unacking new jobs or repeatedly retrying
* seems to be stuck because a configuration file cannot be found inside the container/worker
* Charlie points out that there are recent commits altering the code for this job, see details below

The queue (please infer which one from hints in the bullets) is not operating nominally since May 29th. ([go to rmq](https://mamba-mozart.aria.hysds.io:15673/#/queues/%2F/factotum-job_worker-apihub_scraper_throttled)) One job is unacked but the queue never gets smaller, it only grows larger as new jobs are added to it. The jobs are not processing to completion.

Charlie reported some useful observations in slack, copied here:

>**Charles Z Marshak  23 minutes ago**
>Hey @Jack McNelis @Nicholas W Arena @Marjorie J Lucas and @Rishi Verma
>
>Pretty confident that the queue for these acquisitions is factotum-job_worker-apihub_scraper_throttled. 
>Looks like it is backed up (422 jobs are queued - not sure how long they have been there).
>
>This is the cron: https://github.com/aria-jpl/scihub_acquisition_scraper/blob/0f7d3389e84ca3329479857120e558815b509f0f/crons/acq_ingest_cron.py
>
>And seems like one of the possible entrypoints is: 
>https://github.com/aria-jpl/scihub_acquisition_scraper/blob/0f7d3389e84ca3329479857120e558815b509f0f/docker/job-spec.json.acquisition_ingest-scihub
>
>Looks like we are really far behind in this queue - would be nice to “unclog it” - how was this done previously? (edited) 

List of last modified times for this queue's log files:

```shell
(verdi) ~/verdi/log$ ls -ltrs factotum-job_worker-apihub_scraper_throttled.log*
** <operations user> <operations user> 73401113 May  3 08:45 factotum-job_worker-apihub_scraper_throttled.log.5
** <operations user> <operations user> 73414341 May  3 09:31 factotum-job_worker-apihub_scraper_throttled.log.4
** <operations user> <operations user> 73419289 May 12 05:40 factotum-job_worker-apihub_scraper_throttled.log.3
** <operations user> <operations user> 73419089 May 29 04:27 factotum-job_worker-apihub_scraper_throttled.log.2
** <operations user> <operations user> 73403606 May 29 04:42 factotum-job_worker-apihub_scraper_throttled.log.1
** <operations user> <operations user> 33444022 Jun  9 00:05 factotum-job_worker-apihub_scraper_throttled.log
```

The tail of log number 2:

```shell
$ cat /path/to/verdi/dir/obfuscated/log/factotum-job_worker-apihub_scraper_throttled.log.2 | tail
  File "/path/to/script/obfuscated/scrape_apihub_opensearch.py", line 77, in read_creds
    with open(abs_file_path, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/ops/home/directory/obfuscated/verdi/etc/settings.yaml'
```

The same error as the one reported in Figaro:

```
No such file or directory: '/path/to/ops/home/obfuscated/verdi/etc/settings.yaml'
```

The [Figaro history](https://100.67.33.56/figaro/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsic2hvcnRfZXJyb3IudW50b3VjaGVkIjoiW0Vycm5vIDJdIE5vIHN1Y2ggZmkuLi4uLm5ncy55YW1sJ1xuIn19LHsicXVlcnlfc3RyaW5nIjp7InF1ZXJ5IjoiXCJmYWN0b3R1bS1qb2Jfd29ya2VyLWFwaWh1Yl9zY3JhcGVyX3Rocm90dGxlZFwiIiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzaXplIjoyNSwic29ydCI6W3siQHRpbWVzdGFtcCI6eyJvcmRlciI6ImRlc2MifX1dLCJmaWVsZHMiOlsiQHRpbWVzdGFtcCJdLCJwYXJ0aWFsX2ZpZWxkcyI6eyJfc291cmNlIjp7ImV4Y2x1ZGUiOlsiam9iLmpvYl9pbmZvLm1ldHJpY3MiLCJjb250ZXh0LmNvbnRleHQiLCJjb250ZXh0LmxvY2FsaXplX3VybHMiLCJqb2IuY29udGV4dC5jb250ZXh0Iiwiam9iLmNvbnRleHQuam9iX3NwZWNpZmljYXRpb24ucGFyYW1zIiwiam9iLmNvbnRleHQubG9jYWxpemVfdXJscyIsImpvYi5sb2NhbGl6ZV91cmxzIiwiam9iLnBhcmFtcyJdfX19) for this type of failure only goes back to May 29 -- no previous references to it AFAIK.

## follow up info

As Charlie pointed out, the bug seems to start from this commit or one recently before it: https://github.com/aria-jpl/scihub_acquisition_scraper/commit/0f7d3389e84ca3329479857120e558815b509f0f

Could also be this one, introduces entirely new function to read that file: https://github.com/aria-jpl/scihub_acquisition_scraper/commit/cb2334278b190694ceb93468af87bcadde32914e#diff-2ca0ad8722ad48c7a45a93cf1a485c1858c8b1c072f4669f444b0164723d000eR74

**Comment by cmarshak** [comment]
It’s hard to keep track of all this so for posterity putting some links here in this follow up.

Jobs completed [1] with container (`factotum-job_worker-apihub_scraper_throttled`) and queue(`factotum-job_worker-apihub_scraper_throttled`) discussed.

Docs representing SLC metadata since May 27th [2]. Currently it is at 133 docs and today is June 9th around noon - hopefully the docs slowly increase. I am not seeing real-time increases though - maybe this is due to the jobs searching for missing docs as Nick Arenas pointed out.

[1] https://100.67.33.56/figaro/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsic3RhdHVzIjoiam9iLWNvbXBsZXRlZCJ9fSx7InRlcm0iOnsiam9iLmpvYi5jb250YWluZXJfaW1hZ2VfbmFtZSI6ImNvbnRhaW5lci1hcmlhLWpwbF9zY2lodWJfYWNxdWlzaXRpb25fc2NyYXBlcjpkZXZlbG9wIn19LHsicXVlcnlfc3RyaW5nIjp7InF1ZXJ5IjoiXCJmYWN0b3R1bS1qb2Jfd29ya2VyLWFwaWh1Yl9zY3JhcGVyX3Rocm90dGxlZFwiIiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzaXplIjoyNSwic29ydCI6W3siQHRpbWVzdGFtcCI6eyJvcmRlciI6ImRlc2MifX1dLCJmaWVsZHMiOlsiQHRpbWVzdGFtcCJdLCJwYXJ0aWFsX2ZpZWxkcyI6eyJfc291cmNlIjp7ImV4Y2x1ZGUiOlsiam9iLmpvYl9pbmZvLm1ldHJpY3MiLCJjb250ZXh0LmNvbnRleHQiLCJjb250ZXh0LmxvY2FsaXplX3VybHMiLCJqb2IuY29udGV4dC5jb250ZXh0Iiwiam9iLmNvbnRleHQuam9iX3NwZWNpZmljYXRpb24ucGFyYW1zIiwiam9iLmNvbnRleHQubG9jYWxpemVfdXJscyIsImpvYi5sb2NhbGl6ZV91cmxzIiwiam9iLnBhcmFtcyJdfX19

[2] https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjEtMDUtMjdUMDA6MDA6MDBaIFRPICp9IiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzb3J0IjpbeyJfdGltZXN0YW1wIjp7Im9yZGVyIjoiZGVzYyJ9fV0sImZpZWxkcyI6WyJfdGltZXN0YW1wIiwiX3NvdXJjZSJdfQ==

**Comment by jjmcnelis** [comment]
I'm pretty confident now that the *starttime* and *endttime* parameter issue that I mentioned over email is indeed a bug,  and that it amounts to a total blocker. 

Details copied here: 

>May have found the cause of the bad/non-existent acq metadata: the scrapers (and/or ingesters…) appear to be running with bad parameters for starttime and endtime. They’re set to a date in 2029 in all recent entries in the log on factotum.
>
>The 2029 artifact started showing up during May, according the last modified dates. Run these commands to dump the logs and print the first line with a match for “2029-“
>        cat ~/verdi/log/factotum-job_worker-apihub_scraper_throttled.log | grep '2029-' | head -1
>        cat ~/verdi/log/factotum-job_worker-apihub_scraper_throttled.log.5 | grep '2029-' | head -1
> 
>The first command prints one of the malformed dates in the current/active log file. The second prints nothing because log.5 hasn’t been touched since early May (i.e. before our issue with the metadata scrape/ingest routines). Seems promising. Will let you know if I find something definitive.
> 
>(I put some details in the aria-coseismic-dev channel: https://jpl.slack.com/archives/G016QET5BNF/p1623295432368000 with snippets from the logs. Will sanitize those and put them into the github issue.)

Here's a relevant snippet of log, the same one given in the aria-coseismic-dev slack channel:

```json
“ingest_flag", "value": "--ingest"}, {"destination": "positional", "name": "purpose_flag", "value": "--purpose"}, {"destination": "positional", "name": "purpose", "value": "aoi_scrape"}, {"destination": "positional", "name": "report_flag", "value": "--report"}], "required-queues": ["factotum-job_worker-apihub_scraper_throttled"], "resource": "jobspec", "soft_time_limit": 3300, "time_limit": 3600}, "container_specification": {"digest": "sha256:351869a8a4fb93a1eaacc0702a0c1c755a1b04e21af86e7781c6de94aef40136", "id": "container-aria-jpl_scihub_acquisition_scraper:develop", "url": "s3://s3-us-west-2.amazonaws.com/aria-dev-cc-fwd-torresal/container-aria-jpl_scihub_acquisition_scraper:develop.tar.gz", "version": "develop"}, "aoi_name": "AOITRACK_eq_usgs_neic_pdl_us7000e54r_4", "ds_cfg": "datasets.json", "starttime": "2029-12-01T00:00:00.000000Z",
```

There are wacky timestamps passed to the scihub acquisition scraper jobs: *`"starttime": "2029-12-01T00:00:00.000000Z",`*

**Comment by marjo-luc** [comment]
I think the backlog for this queue is expected given how long the jobs take to run, how often they are being run, and how few instances (1 to be exact) listeners there are for the queue:
_[program:factotum-job_worker-apihub_scraper_throttled]
directory=/export/home/hysdsops/verdi/ops/hysds
environment=HYSDS_ROOT_WORK_DIR="/data/work",
            HYSDS_DATASETS_CFG="/export/home/hysdsops/verdi/etc/datasets.json"
command=celery worker --app=hysds --concurrency=1 --loglevel=INFO -Q factotum-job_worker-apihub_scraper_throttled -n %(program_name)s.%%h -O fair --without-mingle --without-gossip --heartbeat-interval=60
process_name=%(program_name)s
priority=1
numprocs=1
numprocs_start=0
redirect_stderr=true
stdout_logfile=%(here)s/../log/%(program_name)s.log
stdout_logfile_maxbytes=70MB
stdout_logfile_backups=5
startsecs=10_

The settings.yaml error is the pge indicating the file was not copied into the docker container. Which pge produced this error? (there are six or so different acquisition scraper pge's)

**Comment by riverma** [comment]
@jjmcnelis - could you confirm resolution of this ticket per your merged PR? You'd need to coordinate with @marjo-luc to deploy the patch to production and test.

**Comment by cmarshak** [comment]
To add to this, the relevant cron jobs are

```
# Scihub Acquisition Scraper
################################
38 5 * * * LD_LIBRARY_PATH=$HOME/conda/lib:/usr/lib:/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH $HOME/verdi/bin/python /[user-home-directory]/aria_cron_jobs/scihub_acquisition_scraper/crons/acq_ingest_cron.py --tag develop opensearch --days 1 > /[user-home-directory]/verdi/log/cron-scrape_apihub_opensearch.log 2>&1
44 * * * * LD_LIBRARY_PATH=$HOME/conda/lib:/usr/lib:/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH $HOME/verdi/bin/python /[user-home-directory]/aria_cron_jobs/scihub_acquisition_scraper/crons/acq_ingest_cron.py --tag develop opensearch --hours 2 > /[user-home-directory]/verdi/log/cron-scrape_apihub_opensearch.log 2>&1
```

For the coseismic pipeline, we need the acquisition metadata to globally up-to-date before the enumerator runs every 4 hours (the enumerator relies on the metadata acquisition to list the SLCs for GUNWs).

And this is not the case as of yet as can be seen [1] as this facet for datasets since 6-20 (> 24 hours from the time of this post) is empty.

[1] https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjEtMDYtMjBUMDA6MDA6MDBaIFRPICp9IiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzb3J0IjpbeyJfdGltZXN0YW1wIjp7Im9yZGVyIjoiZGVzYyJ9fV0sImZpZWxkcyI6WyJfdGltZXN0YW1wIiwiX3NvdXJjZSJdfQ==

**Comment by riverma** [comment]
Pending review for a few more days / weeks. Application of the associated PR indicates preliminary expected behavior.

**Comment by cmarshak** [comment]
Today it has been working fine.

June 22nd, 2021 facet: https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjEtMDYtMjJUMDA6MDA6MDBaIFRPIDIwMjEtMDYtMjNUMDA6MDA6MDBafSIsImRlZmF1bHRfb3BlcmF0b3IiOiJPUiJ9fV19fSwic29ydCI6W3siX3RpbWVzdGFtcCI6eyJvcmRlciI6ImRlc2MifX1dLCJmaWVsZHMiOlsiX3RpbWVzdGFtcCIsIl9zb3VyY2UiXX0=

June 22nd, 2020 facet: https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjAtMDYtMjJUMDA6MDA6MDBaIFRPIDIwMjAtMDYtMjNUMDA6MDA6MDBafSIsImRlZmF1bHRfb3BlcmF0b3IiOiJPUiJ9fV19fSwic29ydCI6W3siX3RpbWVzdGFtcCI6eyJvcmRlciI6ImRlc2MifX1dLCJmaWVsZHMiOlsiX3RpbWVzdGFtcCIsIl9zb3VyY2UiXX0=

Both roughly have 900 acquisitions over this period. Will have to continue monitoring.

**Comment by jjmcnelis** [comment]
Do the acq scrapers depend on any other datasets? Orbits? I've run the IPF and ACQ scrapers several times and they do not fill the gaps in the acquisition metadata. 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/27017734/123307725-d6728100-d4f0-11eb-9860-1d915982f77f.png">
Example from grq: https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJzdGFydHRpbWU6IHsyMDIxLTA0LTI3VDAwOjAwOjAwWiBUTyAyMDIxLTA0LTI4VDAwOjAwOjAwWn0iLCJkZWZhdWx0X29wZXJhdG9yIjoiT1IifX1dfX0sInNvcnQiOlt7Il90aW1lc3RhbXAiOnsib3JkZXIiOiJkZXNjIn19XSwiZmllbGRzIjpbIl90aW1lc3RhbXAiLCJfc291cmNlIl19

**Comment by cmarshak** [comment]
Hey Jack,

The acq scrapers (I believe) only update _recent_ metadata. Did you run the scrapers over the above AOI?

I think that should solve it? Please clarify.

For others, there are two related issues

1. updating the recent metadata (issue 13: https://github.com/aria-jpl/scihub_acquisition_scraper/issues/13)
2. updating the historical metadata (issue 14: https://github.com/aria-jpl/scihub_acquisition_scraper/issues/14)

**Comment by jjmcnelis** [comment]
> Hey Jack,
> 
> The acq scrapers (I believe) only update _recent_ metadata. Did you run the scrapers over the above AOI?
> 
> I think that should solve it? Please clarify.
> 
> For others, there are two related issues
> 
> 1. updating the recent metadata (issue 13: https://github.com/aria-jpl/scihub_acquisition_scraper/issues/13)
> 2. updating the historical metadata (issue 14: https://github.com/aria-jpl/scihub_acquisition_scraper/issues/14)

Hi Charlie

Yep I have run scrapers numerous times on-demand for the US AOIs and they do not fill the gaps that you and I looked at together (i.e the way you showed me using the free text query to select one day of acq metadata in Tosca) or any other gaps in the historical acq metadata in any other area, for that matter

New metadata retrieval (through the crons) seems to work nominally

**Comment by jjmcnelis** [comment]
Test

**Comment by jjmcnelis** [comment]
Yes, let's close this @riverma . Appears we are ingesting acquisitions nominally: https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJyYW5nZSI6eyJzdGFydHRpbWUiOnsiZnJvbSI6IjIwMjEtMDctMDFUMDA6MDA6MDBaIiwidG8iOiIyMDIxLTA3LTMxVDIzOjU5OjU5WiJ9fX1dfX0sInNvcnQiOlt7Il90aW1lc3RhbXAiOnsib3JkZXIiOiJkZXNjIn19XSwiZmllbGRzIjpbIl90aW1lc3RhbXAiLCJfc291cmNlIl19
