### ISSUE TITLE
Scraper fails, unable to parse MultiPolygon in footprint

### ISSUE THREAD

**Issue by shitong01** [aria-jpl/scihub_acquisition_scraper#2]
Scraper started failing from `S1B_IW_SLC__1SDV_20190306T044941_20190306T045003_015229_01C7DB_79FE`, at ingesting dataset from `2019-03-06T04:49:41.712Z` onwards.

Logs: https://gist.github.com/shitong01/5bf00863b8ac5b4228f7a8500609ed1e

Seems like scihub changed footprint from Polygon to [MultiPolygon](https://gist.github.com/shitong01/5bf00863b8ac5b4228f7a8500609ed1e#file-00-scraper-started-failing-with-s1b_iw_slc__1sdv_20190306t044941_20190306t045003_015229_01c7db_79fe-at-ingestion-from-2019-03-06t04-49-41-712z-onwards-L17) with extra parentheses, causing regex to fail [here](https://github.com/hysds/scihub_acquisition_scraper/blob/master/scrape_apihub_opensearch.py#L61)

Error message:
exception:
```
unexpected EOF while parsing (, line 1)
```

traceback:
```
Traceback (most recent call last):
  File "/home/ops/verdi/ops/scihub_acquisition_scraper/scrape_apihub_opensearch.py", line 327, in 
    args.ingest, args.create_only, args.browse)
  File "/home/ops/verdi/ops/scihub_acquisition_scraper/scrape_apihub_opensearch.py", line 228, in scrape
    try: massage_result(met)
  File "/home/ops/verdi/ops/scihub_acquisition_scraper/scrape_apihub_opensearch.py", line 106, in massage_result
    polygon = [map(eval, coord.split()) for coord in match.group(1).split(',')]
  File "", line 1
    (25.090096
             ^
SyntaxError: unexpected EOF while parsing
```

**Comment by shitong01** [comment]
If we query before March 5th 2019, we will get `POLYGON` only: https://scihub.copernicus.eu/apihub/search?q=IW+AND+producttype%3ASLC+AND+platformname%3ASentinel-1+AND+ingestiondate%3A%5B2019-03-02T11%3A20%3A01.684727Z+TO+2019-03-04T11%3A20%3A01.684792Z%5D&start=0&rows=100&format=json

**Comment by pymonger** [comment]
@shitong: how was this fixed?

**Comment by shitong01** [comment]
These 2 commits 6 months ago:
https://github.com/aria-jpl/scihub_acquisition_scraper/commit/db503bf7e4daa3acbab33ca2dd20c0a691275aed
https://github.com/aria-jpl/scihub_acquisition_scraper/commit/4e3e68dbcda5778b43362c7c04a0215d36383702

**Comment by pymonger** [comment]
Thanks for the reminder.
